name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        - ubuntu-latest
        - macos-latest
        nim:
        - 2.0.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.5.1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nim --version
      - name: Run tests
        run: nimble -y test
